# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b52400a61ede65be4cdd097fe753ba42759abf91fc687bcb13aa13f8b0d7b14d872af9201f81fd68ea3444c2b52f1a45a6c6835da21289138a9c55c453efee9

test:
  secret_key_base: 90fdc49f07d4a5e1eb551b885918141f890da226f8a36eed190d44931d4faf57eea5624c7f4d00cd3ebded889829f0fb026da0276c6eed637143ccc9ee1bf699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
